describe('Automation test cases for final task', () => {
    const email = 'Testing' + Math.floor((Math.random() * 100000)) + '@testing.com';

    it('Create a new user', () => {
        cy.visit('https://lv.sportsdirect.com/')
        cy.get('#divSignIn')
            .should('be.visible')
            .click()
        cy.get('#login')
            .should('be.visible')
        cy.get('[href="/registration?returnUrl=%2f"]')
            .click()
        cy.get('#RegistrationForm')
            .should('be.visible')
        cy.get('#Registration_FirstName')
            .type('Tester')
        cy.get('#Registration_LastName')
            .type('Testing')
        cy.get('#Registration_EmailAddress')
            .type(email)
        cy.get('#Registration_DateOfBirthDay')
            .select('1')
            .should('have.value', '1')
        cy.get('#Registration_DateOfBirthMonth')
            .select('1')
            .should('have.value', '1')
        cy.get('#Registration_DateOfBirthYear')
            .select('1990')
            .should('have.value', '1990')
        cy.get('#txtPassword')
            .type('Qwerty123$%^')
        cy.get('#Registration_ConfirmPassword')
            .type('Qwerty123$%^')
        cy.get('#Registration_IsSubscriber')
            .check()
        cy.get('#RegistrationSubmit')
            .click()
    })

    it('Logging in with a registered user', () => {
        cy.visit('https://lv.sportsdirect.com/')
        cy.get('#divSignIn')
            .should('be.visible')
            .click()
        cy.get('#login')
            .should('be.visible')
        cy.get('#Login_EmailAddress')
            .type(email)
        cy.get('#Login_Password')
            .type('Qwerty123$%^')
        cy.get('#LoginButton')
            .click()
        cy.get('#divAccount')
            .should('be.visible')
            .click()
        cy.get('#accountHeader')
            .should('be.visible')
        cy.get('#accountHeader')
            .children()
            .children('h1')
            .should('have.text', 'Account Details')
    })

    it.only('"Please complete card details" error during checkout as a guest user', () => {
        cy.visit('https://lv.sportsdirect.com/basketball/basketball-shoes')
        cy.get('#ProductContainer')
            .should('be.visible')
        cy.get('#navlist')
            .children()
            .first()
            .click()
        cy.get('#ulSizes')
            .should('be.visible')
        cy.get('#liItem')
            .first()
            .click()
        cy.get('#aAddToBag')
            .click()
        cy.get('#divBagItems')
            .should('be.visible')
        cy.get('#aCheckout')
            .click()
        cy.get('#continue')
            .should('be.visible')
        cy.get('#Guest_EmailAddress')
            .type('Testing' + Math.floor((Math.random() * 100000)) + '@testing.com')
        cy.get('.dnnPrimaryAction')
            .eq(1)
            .should('have.text', 'Continue Securely')
            .click()
        cy.get('#SaveAddressForm')
            .should('be.visible')
        cy.get('#NewAddressSelection_Address_FirstName')
            .type('Tester')
        cy.get('#NewAddressSelection_Address_Surname')
            .type('Testing')
        cy.get('#NewAddressSelection_Address_Line1')
            .type('Random street')
        cy.get('#NewAddressSelection_Address_Town')
            .type('Random town', {force: true})
        cy.get('#NewAddressSelection_Address_Postcode')
            .type('LV1234')
        cy.get('#TelephoneNumber')
            .type('+37121234567', {force: true})
        cy.get('.AddressContainBut.NewAddressContainBut')
            .eq(2)
            .click()
        cy.get('.Delivery')
            .children('h1')
            .should('have.text', 'Delivery Options')
        cy.get('.ContinueOn')
            .eq(2)
            .click({force: true})
        cy.get('#NewCardPaymentForm')
            .should('be.visible')
            .click()
        cy.get('.CardGroup')
            .children('h1')
            .should('have.text', 'Enter your Card Details')
        cy.get('#cardDetailsIncompleteError')
            .should('not.be.visible')
        cy.get('#cardSubmit')
            .click()
        cy.get('#cardDetailsIncompleteError')
            .should('be.visible')
            .and('have.text', 'Please complete the card details to continue.')
    })
})