import {LoginPage} from "../pageObjects/loginPage";
import {RegistrationPage} from "../pageObjects/registrationPage";

describe('Automation test cases for final task', () => {
    const email = 'Testing' + Math.floor((Math.random() * 100000)) + '@testing.com'
    const password = 'Qwerty123$%^'

    it.only('Create a new user', () => {
        cy.visit('https://lv.sportsdirect.com/')
        cy.get('#divSignIn')
            .should('be.visible')
            .click()
        cy.get('#login')
            .should('be.visible')
        cy.get('[href="/registration?returnUrl=%2f"]')
            .click()
        RegistrationPage.registrationFormVisibility()
        RegistrationPage.fillRegistrationForm(email, password)
        RegistrationPage.submitRegistrationForm()
    })

    it('Logging in with a registered user', () => {
        cy.visit('https://lv.sportsdirect.com/')
        cy.get('#divSignIn')
            .should('be.visible')
            .click()
        LoginPage.loginFormVisibility()
        LoginPage.fillLoginForm(email, password)
        LoginPage.clickLoginButton()
        LoginPage.checkAccountInformation()
    })

    it('"Please complete card details" error during checkout as a guest user', () => {
        cy.visit('https://lv.sportsdirect.com/basketball/basketball-shoes')
        cy.get('#ProductContainer')
            .should('be.visible')
        cy.get('#navlist')
            .children()
            .first()
            .click()
        cy.get('#ulSizes')
            .should('be.visible')
        cy.get('#liItem')
            .first()
            .click()
        cy.get('#aAddToBag')
            .click()
        cy.get('#divBagItems')
            .should('be.visible')
        cy.get('#aCheckout')
            .click()
        cy.get('#continue')
            .should('be.visible')
        cy.get('#Guest_EmailAddress')
            .type('Testing' + Math.floor((Math.random() * 100000)) + '@testing.com')
        cy.get('.dnnPrimaryAction')
            .eq(1)
            .should('have.text', 'Continue Securely')
            .click()
        cy.get('#SaveAddressForm')
            .should('be.visible')
        cy.get('#NewAddressSelection_Address_FirstName')
            .type('Tester')
        cy.get('#NewAddressSelection_Address_Surname')
            .type('Testing')
        cy.get('#NewAddressSelection_Address_Line1')
            .type('Random street')
        cy.get('#NewAddressSelection_Address_Town')
            .type('Random town', {force: true})
        cy.get('#NewAddressSelection_Address_Postcode')
            .type('LV1234')
        cy.get('#TelephoneNumber')
            .type('+37121234567', {force: true})
        cy.get('.AddressContainBut.NewAddressContainBut')
            .eq(2)
            .click()
        cy.get('.Delivery')
            .children('h1')
            .should('have.text', 'Delivery Options')
        cy.get('.ContinueOn')
            .eq(2)
            .click({force: true})
        cy.get('#NewCardPaymentForm')
            .should('be.visible')
            .click()
        cy.get('.CardGroup')
            .children('h1')
            .should('have.text', 'Enter your Card Details')
        cy.get('#cardDetailsIncompleteError')
            .should('not.be.visible')
        cy.get('#cardSubmit')
            .click()
        cy.get('#cardDetailsIncompleteError')
            .should('be.visible')
            .and('have.text', 'Please complete the card details to continue.')
    })
})